name: "QCoDeS_driver_contrib CI"

# A note on activating conda environments
# At the time of writing the prefered way to activate conda envs (conda 4.6.x)
# is to use conda activate env, and source activate is deprecated. However, this
# requires the user to run conda init which will configure a startup hook for the relevant terminal
# However, azure pipelines does (at the time of writing may 2019) not execute the hook scrips in cmd.exe or bash
# To work around this we use standard source activate qcodes in bash and run the hook manually in cmd.exe
# The hook needs to be rerun for each step.
# We could also run the hooks for bash steps but there is no obvious way to do that in a platform independent way.

trigger:
  branches:
    include:
      - master

jobs:
  - job: "run_the_tests"
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-16.04'
        windows:
          imageName: 'vs2017-win2016'
    pool:
      vmImage: $(imageName)

    steps:
      - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
        displayName: "Add conda to PATH on Windows"
        condition: eq( variables['Agent.OS'], 'Windows_NT' )
      - bash: echo "##vso[task.prependpath]/usr/share/miniconda/bin"
        displayName: "Add conda to PATH on Linux"
        condition: eq( variables['Agent.OS'], 'Linux' )
      - script: |
          conda install conda=4.6 -n base -y
          conda init --all
        displayName: "Conda setup on Windows"
        condition: eq( variables['Agent.OS'], 'Windows_NT' )
      - bash: |
          sudo conda update -n base conda -y
          sudo conda init bash
        displayName: "Conda setup on Linux"
        condition: eq( variables['Agent.OS'], 'Linux' )
      - bash: |
          conda --version
          curl https://raw.githubusercontent.com/QCoDeS/Qcodes/master/environment.yml > environment.yml
          curl https://raw.githubusercontent.com/QCoDeS/Qcodes/master/environment.yml > test_requirements.txt
          curl https://raw.githubusercontent.com/QCoDeS/Qcodes/master/environment.yml > docs_requirements.txt
          conda env create --file environment.yml
          source activate qcodes
          pip install -r test_requirements.txt
          pip install -r docs_requirements.txt
          pip install -e .
        displayName: "Install environment, qcodes"
      - bash: |
          source activate qcodes
          mypy qcodes
        displayName: "mypy"
      - script: |
          CALL C:\Miniconda\condabin\conda_hook.bat
          CALL conda activate qcodes
          cd qcodes_contrib_drivers
          pytest --junitxml=test-results.xml --cov=qcodes --cov-report=xml --cov-report=html --cov-config=.coveragerc
        displayName: "Pytest on Windows"
        condition: and(succeededOrFailed(), eq( variables['Agent.OS'], 'Windows_NT' ))
      - bash: |
          source activate qcodes
          cd qcodes_contrib_drivers
          xvfb-run --server-args="-screen 0 1024x768x24" pytest --junitxml=test-results.xml --cov=qcodes --cov-report=xml --cov-report=html --cov-config=.coveragerc
        displayName: "Pytest on Linux"
        condition: and(succeededOrFailed(), eq( variables['Agent.OS'], 'Linux' ))
      - task: PublishTestResults@1
        displayName: "Publish test results"
        condition: succeededOrFailed()
        inputs:
          testResultsFiles: 'qcodes_contrib_drivers/test-*.xml'
          testRunTitle: 'Publish test results'
      - task: PublishCodeCoverageResults@1
        displayName: "Publish code coverage results"
        condition: succeededOrFailed()
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/qcodes_contrib_drivers/coverage.xml'
      - script: |
          CALL C:\Miniconda\condabin\conda_hook.bat
          CALL conda activate qcodes
          cd docs
          REM Turn warnings into errors
          set SPHINXOPTS=-W -v
          make.bat html
        displayName: "Build docs on Windows"
        condition: and(succeededOrFailed(), eq( variables['Agent.OS'], 'Windows_NT' ))
      - script: |
          source activate qcodes
          cd docs
          export SPHINXOPTS=-W -v
          xvfb-run --server-args="-screen 0 1024x768x24" make html
        displayName: "Build docs on Linux"
        condition: and(succeededOrFailed(), eq( variables['Agent.OS'], 'Linux' ))
      - task: PublishBuildArtifacts@1
        displayName: "Publish build docs to Azure DevOps"
        condition: succeededOrFailed()
        inputs:
          pathtoPublish: 'docs/_build/html'
          artifactName: 'qcodes_docs'
          publishLocation: 'Container'
